### ISSUE TITLE
File link broken

### ISSUE THREAD

**Issue by kundezui** [LuigiFederico/PatchCore-for-Industrial-Anomaly-Detection#8]
Sorry, all the files you linked do not exist. Can you update the file address?

**Comment by LuigiFederico** [comment]
I'm sincerely sorry but I can't find the colab notebook. It was an academic project shared between us (the authors listed inside the README file), and I sadly not have access to the old account. I've tryed to recover it but sadly I did not find the credentials.

In any case, the colab notebook just imported the libraries and used the code written inside the files that you find in the lib folder.

To be fair for future visitors of this repository, I deleted the links to the colab notebook inside the README file. :)
